
required = [
  # Needed for build
  "github.com/jteeuwen/go-bindata/go-bindata",

  # Needed for apimachinery generation
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
]

[prune]
  go-tests = true
  unused-packages = true


# Note that the older version specified in k8s.io/kubernetes Godeps breaks go dep
[[override]]
  name = "github.com/chai2010/gettext-go"
  revision = "bf70f2a70fb1b1f36d90d671a72795984eab0fcb"

# aws-sdk-go is one of our critical dependencies
[[override]]
  name = "github.com/aws/aws-sdk-go"
  revision = "bff41fb23b7550368282029f6478819d6a99ae0f"
  #version = "v1.12.79"

# We need this for our build
[[override]]
  name = "github.com/jteeuwen/go-bindata"
  revision = "a0ff2567cfb70903282db057e799fd826784d41d"

# Needed for apimachinery generation
[[override]]
  name = "k8s.io/code-generator"
  revision = "91d3f6a57905178524105a085085901bb73bd3dc"

# These come from godeps.json in kubernetes
[[override]]
  name = "github.com/hashicorp/hcl"
  revision = "d8c773c4cba11b11539e3d45f93daeaa5dcf1fa1"
[[override]]
  name = "github.com/spf13/cobra"
  revision = "f62e98d28ab7ad31d707ba837a966378465c7b57"
[[override]]
  name = "golang.org/x/crypto"
  revision = "81e90905daefcd6fd217b62423c0908922eadb30"
[[override]]
  name = "github.com/go-openapi/spec"
  revision = "7abd5745472fff5eb3685386d5fb8bf38683154d"
[[override]]
  name = "github.com/go-openapi/swag"
  revision = "f3f9494671f93fcff853e3c6e9e948b3eb71e590"
[[override]]
  name = "k8s.io/api"
  revision = "acf347b865f29325eb61f4cd2df11e86e073a5ee"
[[override]]
  name = "github.com/gogo/protobuf"
  revision = "c0656edd0d9eab7c66d1eb0c568f9039345796f7"
[[override]]
  name = "golang.org/x/sys"
  revision = "95c6576299259db960f6c5b9b69ea52422860fce"
[[override]]
  name = "github.com/gregjones/httpcache"
  revision = "787624de3eb7bd915c329cba748687a3b22666a6"
[[override]]
  name = "gopkg.in/gcfg.v1"
  revision = "27e4946190b4a327b539185f2b5b1f7c84730728"
# UNKNOWN dep github.com/tent/http-link-go
[[override]]
  name = "github.com/go-openapi/jsonreference"
  revision = "13c6e3589ad90f49bd3e3bbe2c2cb3d7a4142272"
[[override]]
  name = "k8s.io/utils"
  revision = "aedf551cdb8b0119df3a19c65fde413a13b34997"
[[override]]
  name = "github.com/docker/docker"
  revision = "4f3616fb1c112e206b88cb7a9922bf49067a7756"
[[override]]
  name = "github.com/fatih/camelcase"
  revision = "f6a740d52f961c60348ebb109adde9f4635d7540"
[[override]]
  name = "k8s.io/kube-openapi"
  revision = "39a7bf85c140f972372c2a0d1ee40adbf0c8bfe1"
[[override]]
  name = "github.com/NYTimes/gziphandler"
  revision = "56545f4a5d46df9a6648819d1664c3a03a13ffdb"
[[override]]
  name = "github.com/renstrom/dedent"
  revision = "020d11c3b9c0c7a3c2efcc8e5cf5b9ef7bcea21f"
[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "8183543f90d1aef267a5ecc209f2e0715b355acb"
[[override]]
  name = "gopkg.in/warnings.v0"
  revision = "8a331561fe74dadba6edfc59f3be66c22c3b065d"
[[override]]
  name = "github.com/json-iterator/go"
  revision = "36b14963da70d11297d313183d7e6388c8510e1e"
[[override]]
  name = "github.com/PuerkitoBio/purell"
  revision = "8a290539e2e8629dbc4e6bad948158f790ec31f4"
[[override]]
  name = "github.com/prometheus/client_model"
  revision = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6"
[[override]]
  name = "github.com/googleapis/gnostic"
  revision = "0c5108395e2debce0d731cf0287ddf7242066aba"
[[override]]
  name = "github.com/inconshreveable/mousetrap"
  revision = "76626ae9c91c4f2a10f34cad8ce83ea42c93bb75"
[[override]]
  name = "google.golang.org/api"
  revision = "654f863362977d69086620b5f72f13e911da2410"
# UNKNOWN dep github.com/petar/GoLLRB
[[override]]
  name = "github.com/Microsoft/go-winio"
  revision = "78439966b38d69bf38227fbf57ac8a6fee70f69a"
[[override]]
  name = "github.com/pkg/sftp"
  revision = "4d0e916071f68db74f8a73926335f809396d6b42"
[[override]]
  name = "github.com/pborman/uuid"
  revision = "ca53cad383cad2479bbba7f7a1a05797ec1386e4"
[[override]]
  name = "github.com/vmware/govmomi"
  revision = "b8b228cfbad7f0a69ed90393ca9aee085d3c6ef1"
[[override]]
  name = "github.com/coreos/go-systemd"
  revision = "48702e0da86bd25e76cfef347e2adeb434a0d0a6"
[[override]]
  name = "github.com/PuerkitoBio/urlesc"
  revision = "5bd2802263f21d8788851d5305584c82a5c75d7e"
[[override]]
  name = "github.com/google/btree"
  revision = "7d79101e329e5a3adf994758c578dab82b90c017"
[[override]]
  name = "github.com/docker/spdystream"
  revision = "449fdfce4d962303d702fec724ef0ad181c92528"
[[override]]
  name = "github.com/dgrijalva/jwt-go"
  revision = "01aeca54ebda6e0fbfafd0a524d234159c05ec20"
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"
[[override]]
  name = "github.com/fsnotify/fsnotify"
  revision = "f12c6236fe7b5cf6bcf30e5935d08cb079d78334"
[[override]]
  name = "github.com/coreos/go-semver"
  revision = "568e959cd89871e61434c1143528d9162da89ef2"
[[override]]
  name = "google.golang.org/grpc"
  revision = "d2e1b51f33ff8c5e4a15560ff049d200e83726c5"
[[override]]
  name = "golang.org/x/oauth2"
  revision = "a6bd8cefa1811bd24b86f8902872e4e8225f74c4"
# UNKNOWN dep github.com/aokoli/goutils
[[override]]
  name = "github.com/MakeNowJust/heredoc"
  revision = "bb23615498cded5e105af4ce27de75b089cbe851"
[[override]]
  name = "github.com/cpuguy83/go-md2man"
  revision = "71acacd42f85e5e82f70a55327789582a5200a90"
[[override]]
  name = "github.com/ugorji/go"
  revision = "ded73eae5db7e7a0ef6f55aace87a2873c5d2b74"
[[override]]
  name = "github.com/elazarl/go-bindata-assetfs"
  revision = "3dcc96556217539f50599357fb481ac0dc7439b9"
# UNKNOWN dep github.com/google/go-querystring
[[override]]
  name = "github.com/imdario/mergo"
  revision = "6633656539c1639d9d78127b7d47c622b5d7b6dc"
[[override]]
  name = "google.golang.org/genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"
[[override]]
  name = "github.com/pkg/errors"
  revision = "645ef00459ed84a119197bfb8d8205042c6df63d"
[[override]]
  name = "github.com/golang/glog"
  revision = "44145f04b68cf362d9c4df2182967c2275eaefed"
[[override]]
  name = "k8s.io/client-go"
  revision = "9389c055a838d4f208b699b3c7c51b70f2368861"
[[override]]
  name = "github.com/docker/go-units"
  revision = "9e638d38cf6977a37a8ea0078f3ee75a7cdb2dd1"
[[override]]
  name = "github.com/Azure/go-ansiterm"
  revision = "19f72df4d05d31cbe1c56bfc8045c96babff6c7e"
[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "e14a70c556c8e0db173358d1a903dca345a8e75e"
[[override]]
  name = "golang.org/x/net"
  revision = "1c05540f6879653db88113bc4a2b70aec4bd491f"
[[override]]
  name = "golang.org/x/text"
  revision = "b19bf474d317b857955b12035d2c5acb57ce8b01"
[[override]]
  name = "gopkg.in/yaml.v2"
  revision = "53feefa2559fb8dfa8d81baad31be332c97d6c77"
[[override]]
  name = "gopkg.in/natefinch/lumberjack.v2"
  revision = "20b71e5b60d756d3d2f80def009790325acc2b23"
[[override]]
  name = "github.com/google/cadvisor"
  revision = "1e567c2ac359c3ed1303e0c80b6cf08edefc841d"
[[override]]
  name = "gopkg.in/inf.v0"
  revision = "3887ee99ecf07df5b447e9b00d9c0b2adaa9f3e4"
[[override]]
  name = "github.com/mitchellh/mapstructure"
  revision = "53818660ed4955e899c0bcafa97299a388bd7c8e"
[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"
[[override]]
  name = "github.com/spf13/jwalterweatherman"
  revision = "33c24e77fb80341fe7130ee7c594256ff08ccc46"
# UNKNOWN dep google.golang.org/appengine
[[override]]
  name = "github.com/spf13/viper"
  revision = "7fb2782df3d83e0036cc89f461ed0422628776f4"
[[override]]
  name = "github.com/spf13/afero"
  revision = "b28a7effac979219c2a2ed6205a4d70e4b1bcd02"
[[override]]
  name = "github.com/peterbourgon/diskv"
  revision = "5f041e8faa004a95c88a202771f4cc3e991971e6"
[[override]]
  name = "github.com/prometheus/common"
  revision = "13ba4ddd0caa9c28ca7b7bffe1dfa9ed8d5ef207"
[[override]]
  name = "github.com/spf13/cast"
  revision = "e31f36ffc91a2ba9ddb72a4b6a607ff9b3d3cb63"
[[override]]
  name = "github.com/pelletier/go-toml"
  revision = "0049ab3dc4c4c70a9eee23087437b69c0dde2130"
[[override]]
  name = "github.com/google/gofuzz"
  revision = "44d81051d367757e1c7c6a5a86423ece9afcf63c"
[[override]]
  name = "github.com/golang/protobuf"
  revision = "1643683e1b54a9e88ad26d98f81400c8c9d9f4f9"
[[override]]
  name = "github.com/jonboulle/clockwork"
  revision = "72f9bd7c4e0c2a40055ab3d0f09654f730cce982"
[[override]]
  name = "k8s.io/apimachinery"
  revision = "19e3f5aa3adca672c153d324e6b7d82ff8935f03"
[[override]]
  name = "github.com/go-openapi/jsonpointer"
  revision = "46af16f9f7b149af66e5d1bd010e3574dc06de98"
[[override]]
  name = "github.com/prometheus/client_golang"
  revision = "e7e903064f5e9eb5da98208bae10b475d4db0f8c"
[[override]]
  name = "github.com/spf13/pflag"
  revision = "9ff6c6923cfffbcd502984b8e0c80539a94968b7"
[[override]]
  name = "github.com/jmespath/go-jmespath"
  revision = "0b12d6b521d83fc7f755e7cfc1b1fbdd35a01a74"
[[override]]
  name = "github.com/prometheus/procfs"
  revision = "65c1f6f8f0fc1e2185eb9863a3bc751496404259"
[[override]]
  name = "github.com/matttproud/golang_protobuf_extensions"
  revision = "fc2b8d3a73c4867e51861bbdd5ae3c1f0869dd6a"
[[override]]
  name = "github.com/ghodss/yaml"
  revision = "73d445a93680fa1a78ae23a5839bad48f32ba1ee"
[[override]]
  name = "github.com/emicklei/go-restful-swagger12"
  revision = "dcef7f55730566d41eae5db10e7d6981829720f6"
[[override]]
  name = "github.com/beorn7/perks"
  revision = "3ac7bf7a47d159a033b107610db8a1b6575507a4"
[[override]]
  name = "github.com/blang/semver"
  revision = "b38d23b8782a487059e8fc8773e9a5b228a77cb6"
[[override]]
  name = "github.com/docker/go-connections"
  revision = "3ede32e2033de7505e6500d6c868c2b9ed9f169d"
# UNKNOWN dep github.com/coredns/coredns
[[override]]
  name = "k8s.io/apiserver"
  revision = "40b00dd493d8fb98c255f0c6427f97fbf865a538"
[[override]]
  name = "github.com/magiconair/properties"
  revision = "61b492c03cf472e0c6419be5899b8e0dc28b1b88"
[[override]]
  name = "github.com/golang/groupcache"
  revision = "02826c3e79038b59d737d3b1c0a1d937f71a4433"
[[override]]
  name = "k8s.io/metrics"
  revision = "f3733640389abc59db26dfca07debf6cb31b7e91"
[[override]]
  name = "cloud.google.com/go"
  revision = "3b1ae45394a234c385be014e9a488f2bb6eef821"
[[override]]
  name = "k8s.io/apiextensions-apiserver"
  revision = "6f29dd12234812844d29f52bd520bb01374619ce"
[[override]]
  name = "github.com/daviddengcn/go-colortext"
  revision = "511bcaf42ccd42c38aba7427b6673277bf19e2a1"
[[override]]
  name = "github.com/miekg/dns"
  revision = "5d001d020961ae1c184f9f8152fdc73810481677"
[[override]]
  name = "k8s.io/kubernetes"
  revision = "049d98c78fb6ec4b260c4f9513e2a9fd57cfe009"
[[override]]
  name = "github.com/juju/ratelimit"
  revision = "5b9ff866471762aa2ab2dced63c9fb6f53921342"
[[override]]
  name = "github.com/davecgh/go-spew"
  revision = "782f4967f2dc4564575ca782fe2d04090b5faca8"
[[override]]
  name = "github.com/mailru/easyjson"
  revision = "2f5df55504ebc322e4d52d34df6a1f5b503bf26d"
[[override]]
  name = "github.com/emicklei/go-restful"
  revision = "ff4f55a206334ef123e4f79bbf348980da81ca46"
[[override]]
  name = "github.com/hashicorp/golang-lru"
  revision = "a0d98a5f288019575c6d1f4bb1573fef2d1fcdc4"
[[override]]
  name = "github.com/coreos/etcd"
  revision = "960f4604bc821241b94906da5fe7f66306a77472"
[[override]]
  name = "vbom.ml/util"
  revision = "db5cfe13f5cc80a4990d98e2e1b0707a4d1a5394"




# These are our dependencies, with the versions we previously locked to with submodules
[[override]]
  name = "github.com/Masterminds/semver"
  revision = "517734cc7d6470c0d07130e40fd40bdeb9bcd3fd"
[[override]]
  name = "github.com/Masterminds/sprig"
  revision = "e039e20e500c2c025d9145be375e27cf42a94174"
[[override]]
  name = "github.com/coreos/pkg"
  revision = "fa29b1d70f0beaddd4c7021607cc3c3be8ce94b8"
[[override]]
  name = "github.com/digitalocean/godo"
  revision = "34840385860db94c88d044571153b6a200ca40b2"
[[override]]
  name = "github.com/docker/engine-api"
  revision = "dea108d3aa0c67d7162a3fd8aa65f38a430019fd"
[[override]]
  name = "github.com/grpc-ecosystem/go-grpc-prometheus"
  revision = "2500245aa6110c562d17020fb31a2c133d737799"
[[override]]
  name = "github.com/grpc-ecosystem/grpc-gateway"
  revision = "84398b94e188ee336f307779b57b3aa91af7063c"
[[override]]
  name = "github.com/huandu/xstrings"
  revision = "3959339b333561bf62a38b424fd41517c2c90f40"
[[override]]
  name = "github.com/miekg/coredns"
  revision = "20e25559d5eada5a68a0720816a6e947b94860ce"
[[override]]
  name = "github.com/opencontainers/go-digest"
  revision = "a6d0ee40d4207ea02364bd3b9e8e77b9159ba1eb"
[[override]]
  name = "github.com/opencontainers/image-spec"
  revision = "372ad780f63454fbbbbcc7cf80e5b90245c13e13"
[[override]]
  name = "github.com/pelletier/go-buffruneio"
  revision = "df1e16fde7fc330a0ca68167c23bf7ed6ac31d6d"
[[override]]
  name = "github.com/satori/go.uuid"
  revision = "5bf94b69c6b68ee1b541973bb8e1144db23a194b"
[[override]]
  name = "github.com/sergi/go-diff"
  revision = "552b4e9bbdca9e5adafd95ee98c822fdd11b330b"
[[override]]
  name = "github.com/shurcooL/sanitized_anchor_name"
  revision = "10ef21a441db47d8b13ebcc5fd2310f636973c77"
[[override]]
  name = "github.com/sirupsen/logrus"
  revision = "89742aefa4b206dcf400792f3bd35b542998eb3b"
[[override]]
  name = "github.com/weaveworks/mesh"
  revision = "1f158d31de55abf9f97bbaa0a260e2b8023a3785"
