apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kops-api-server
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kops
    spec:
      containers:
      - name: kops
        image: krisnova/kops:latest
        ports:
        - containerPort: 80