apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kops-etcd
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: etcd
        image: quay.io/coreos/etcd:latest
        ports:
        - containerPort: 2379